### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by matz-e** [imatlopez/vscode-neuron#6]
Hi, any chance this repo could get a proper license? I'm trying to get Github to recognize NMODL as a language, and they have the option to include syntax highlighting as long as the license is compatible:

https://github.com/github-linguist/linguist/blob/9b1023ed5d308cb3363a882531dea1e272b59977/vendor/licenses/config.yml#L4-L15

**Comment by imatlopez** [comment]
Sorry for the delay, have had this in inbox as a todo. 0c16f6e should suffice?

**Comment by matz-e** [comment]
Thank you!
